// Vercel Serverless Function: GET /api/community/members
import { getSupabase, isSupabaseConfigured } from '../_lib/supabase.js';

// Authoritative public-evidence Dlicom community seed records
const OFFICIAL_SEED_MEMBERS = [
  {
    dliId: 'DLI-CORE-001',
    xHandle: 'dlicomapp',
    normalizedHandle: 'dlicomapp',
    displayName: 'Dlicom',
    role: 'Core Team',
    verificationLevel: 'OFFICIALLY_VERIFIED',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_WEBSITE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://dlicom.me/',
      'https://whitepaper.dlicom.io/',
      'https://x.com/DlicomApp',
    ],
    evidenceSummary: 'Official Dlicom platform primary handle directly embedded in header, footer, metadata, and app connection protocols across dlicom.io.',
    evidence: 'Official Dlicom platform primary handle directly embedded in header, footer, metadata, and app connection protocols across dlicom.io.',
    provenance: 'Sourced from dlicom.io production web bundle (twitter:title, og:url, header and footer social links).',
    confidenceScore: 100,
    discoverySource: 'dlicom.io official platform identity',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/DlicomApp',
    bio: 'AI-powered SocialFi – encrypted messaging, DliClips, self-custody wallet, on-chain tipping.',
  },
  {
    dliId: 'DLI-CORE-002',
    xHandle: 'mohammadqadriah',
    normalizedHandle: 'mohammadqadriah',
    displayName: 'Mohammad Qadriah',
    role: 'Core Team',
    verificationLevel: 'OFFICIALLY_VERIFIED',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_WEBSITE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://whitepaper.dlicom.io/',
      'https://x.com/MohammadQadriah',
    ],
    evidenceSummary: 'Formally published as Chairman & Co-Founder on the official dlicom.io leadership roster and author of the Dlicom Manifesto.',
    evidence: 'Formally published as Chairman & Co-Founder on the official dlicom.io leadership roster and author of the Dlicom Manifesto.',
    provenance: 'Extracted from dlicom.io team section: designation "Chairman & Co-Founder". Cross-referenced with whitepaper.',
    confidenceScore: 100,
    discoverySource: 'dlicom.io leadership roster — Chairman & Co-Founder',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/MohammadQadriah',
    bio: 'Chairman & Co-Founder @DlicomApp. Architect of the Dlicom SocialFi ecosystem on Base.',
  },
  {
    dliId: 'DLI-CORE-003',
    xHandle: 'georgechahine',
    normalizedHandle: 'georgechahine',
    displayName: 'George Chahine',
    role: 'Core Team',
    verificationLevel: 'OFFICIALLY_VERIFIED',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_WEBSITE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://whitepaper.dlicom.io/',
      'https://hacken.io/audits/dlicom/sca-dlicom-token-feb2026/',
      'https://x.com/GeorgeChahine',
    ],
    evidenceSummary: 'Officially designated as CFO & Head of Tokenomics on the dlicom.io core team roster and tokenomics architect in the official Hacken audit.',
    evidence: 'Officially designated as CFO & Head of Tokenomics on the dlicom.io core team roster and tokenomics architect in the official Hacken audit.',
    provenance: 'Extracted from dlicom.io team section: designation "CFO & Head of Tokenomics". Corroborated by Hacken security audit documentation.',
    confidenceScore: 100,
    discoverySource: 'dlicom.io leadership roster — CFO & Head of Tokenomics',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/GeorgeChahine',
    bio: 'CFO & Head of Tokenomics @DlicomApp ($DLI on Base).',
  },
  {
    dliId: 'DLI-CORE-004',
    xHandle: 'jimish_parekh',
    normalizedHandle: 'jimish_parekh',
    displayName: 'Jimish Parekh',
    role: 'Core Team',
    verificationLevel: 'OFFICIALLY_VERIFIED',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_WEBSITE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://whitepaper.dlicom.io/',
      'https://x.com/jimish_parekh',
    ],
    evidenceSummary: 'Formally listed as Chief Technology Officer on the dlicom.io core leadership team, responsible for smart contracts and core infrastructure.',
    evidence: 'Formally listed as Chief Technology Officer on the dlicom.io core leadership team, responsible for smart contracts and core infrastructure.',
    provenance: 'Extracted from dlicom.io team section: designation "CTO". Verified engineering lead on Dlicom Base contracts.',
    confidenceScore: 100,
    discoverySource: 'dlicom.io leadership roster — CTO',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/jimish_parekh',
    bio: 'CTO @DlicomApp. Building decentralized social infrastructure & smart contracts.',
  },
  {
    dliId: 'DLI-CORE-005',
    xHandle: 'timur_akhmatov',
    normalizedHandle: 'timur_akhmatov',
    displayName: 'Timur Akhmatov',
    role: 'Core Team',
    verificationLevel: 'OFFICIALLY_VERIFIED',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_WEBSITE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://x.com/timur_akhmatov',
    ],
    evidenceSummary: 'Officially published as Chief Marketing Officer on the dlicom.io core team section, leading public growth and ecosystem marketing.',
    evidence: 'Officially published as Chief Marketing Officer on the dlicom.io core team section, leading public growth and ecosystem marketing.',
    provenance: 'Extracted from dlicom.io team section: designation "CMO". Corroborated with public growth initiatives.',
    confidenceScore: 100,
    discoverySource: 'dlicom.io leadership roster — CMO',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/timur_akhmatov',
    bio: 'CMO @DlicomApp. Scaling Web3 community & social growth.',
  },
  {
    dliId: 'DLI-LEAD-001',
    xHandle: 'mohamedbelal',
    normalizedHandle: 'mohamedbelal',
    displayName: 'Mohamed Belal',
    role: 'Regional Lead',
    verificationLevel: 'OFFICIAL_COMMUNITY_ROLE',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_COMMUNITY_SOURCE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://t.me/DlicomAppOfficial',
      'https://x.com/MohamedBelal',
    ],
    evidenceSummary: 'Officially published as Head of MENA on the official dlicom.io team section, directing regional community expansion and Arabic-speaking community operations.',
    evidence: 'Officially published as Head of MENA on the official dlicom.io team section, directing regional community expansion and Arabic-speaking community operations.',
    provenance: 'Extracted from dlicom.io regional leadership directory: designation "Head of MENA". Cross-verified with official regional community hubs.',
    confidenceScore: 94,
    discoverySource: 'dlicom.io regional leadership — Head of MENA',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/MohamedBelal',
    bio: 'Head of MENA @DlicomApp. Community leadership & regional expansion.',
    region: 'MENA',
  },
  {
    dliId: 'DLI-CORE-006',
    xHandle: 'alex_dlicom',
    normalizedHandle: 'alex_dlicom',
    displayName: 'Alex',
    role: 'Core Team',
    verificationLevel: 'OFFICIALLY_VERIFIED',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_WEBSITE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://x.com/Alex_Dlicom',
    ],
    evidenceSummary: 'Officially listed as Art Director on the dlicom.io core team, architecting the visual design system and UI/UX assets.',
    evidence: 'Officially listed as Art Director on the dlicom.io core team, architecting the visual design system and UI/UX assets.',
    provenance: 'Extracted from dlicom.io team section: designation "Art Director".',
    confidenceScore: 100,
    discoverySource: 'dlicom.io leadership roster — Art Director',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/Alex_Dlicom',
    bio: 'Art Director @DlicomApp. Visual identity, brand design, and UI/UX.',
  },
  {
    dliId: 'DLI-CORE-007',
    xHandle: 'kirageneralskaya',
    normalizedHandle: 'kirageneralskaya',
    displayName: 'Kira Generalskaya',
    role: 'Core Team',
    verificationLevel: 'OFFICIALLY_VERIFIED',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_WEBSITE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://x.com/kirageneralskaya',
    ],
    evidenceSummary: 'Officially published on dlicom.io team roster as Global Head of Social Media, managing communications across public channels.',
    evidence: 'Officially published on dlicom.io team roster as Global Head of Social Media, managing communications across public channels.',
    provenance: 'Extracted from dlicom.io team section: designation "Global Head of Social Media".',
    confidenceScore: 100,
    discoverySource: 'dlicom.io leadership roster — Global Head of Social Media',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/kirageneralskaya',
    bio: 'Global Head of Social Media @DlicomApp.',
  },
  {
    dliId: 'DLI-CORE-008',
    xHandle: 'mohamedkilany',
    normalizedHandle: 'mohamedkilany',
    displayName: 'Mohamed Kilany',
    role: 'Core Team',
    verificationLevel: 'OFFICIALLY_VERIFIED',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_WEBSITE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://x.com/mohamedkilany',
    ],
    evidenceSummary: 'Officially listed as Product Manager on the dlicom.io team section, overseeing product roadmap and feature rollout.',
    evidence: 'Officially listed as Product Manager on the dlicom.io team section, overseeing product roadmap and feature rollout.',
    provenance: 'Extracted from dlicom.io team section: designation "Product Manager".',
    confidenceScore: 100,
    discoverySource: 'dlicom.io leadership roster — Product Manager',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/mohamedkilany',
    bio: 'Product Manager @DlicomApp.',
  },
  {
    dliId: 'DLI-CORE-009',
    xHandle: 'salmanahmed',
    normalizedHandle: 'salmanahmed',
    displayName: 'Salman Ahmed',
    role: 'Core Team',
    verificationLevel: 'OFFICIALLY_VERIFIED',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_WEBSITE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://x.com/salmanahmed',
    ],
    evidenceSummary: 'Officially published on dlicom.io team directory as Product Designer, responsible for product interface design.',
    evidence: 'Officially published on dlicom.io team directory as Product Designer, responsible for product interface design.',
    provenance: 'Extracted from dlicom.io team section: designation "Product Designer".',
    confidenceScore: 100,
    discoverySource: 'dlicom.io leadership roster — Product Designer',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/salmanahmed',
    bio: 'Product Designer @DlicomApp.',
  },
  {
    dliId: 'DLI-LEAD-002',
    xHandle: 'oleksandrsamofal',
    normalizedHandle: 'oleksandrsamofal',
    displayName: 'Oleksandr Samofal',
    role: 'Community Manager',
    verificationLevel: 'OFFICIAL_COMMUNITY_ROLE',
    verificationStatus: 'VERIFIED',
    sourceType: 'OFFICIAL_COMMUNITY_SOURCE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://discord.gg/yZdYa48gQM',
      'https://x.com/oleksandrsamofal',
    ],
    evidenceSummary: 'Officially published as Community Manager on the dlicom.io team directory, actively managing Dlicom community operations including Dliever, Dcoded, and DCO programs.',
    evidence: 'Officially published as Community Manager on the dlicom.io team directory, actively managing Dlicom community operations including Dliever, Dcoded, and DCO programs.',
    provenance: 'Extracted from dlicom.io team directory: designation "Community Manager". Cross-verified in official Dlicom Discord hub.',
    confidenceScore: 94,
    discoverySource: 'dlicom.io team directory — Community Manager',
    firstVerifiedAt: '2026-09-03T00:00:00Z',
    verifiedAt: '2026-09-03T00:00:00Z',
    lastVerifiedAt: '2026-09-03T00:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/oleksandrsamofal',
    bio: 'Community Manager @DlicomApp. Managing Dliever, Dcoded, and DCO community initiatives.',
  },
];

const CANDIDATE_MEMBERS = [
  {
    dliId: 'DLI-CAND-001',
    xHandle: '0xZeeve',
    normalizedHandle: '0xzeeve',
    displayName: 'Zeeve',
    role: 'Community Candidate',
    verificationLevel: 'COMMUNITY_CANDIDATE',
    verificationStatus: 'CANDIDATE',
    sourceType: 'PUBLIC_X_EVIDENCE',
    officialSourceUrl: 'https://x.com/DlicomApp',
    evidenceUrls: [
      'https://x.com/DlicomApp',
      'https://x.com/0xZeeve',
    ],
    evidenceSummary: 'Publicly observable infrastructure rollout partnership mentioned in official DlicomApp public posts. Classified strictly as Candidate pending formal leadership or core-roster inclusion.',
    evidence: 'Publicly observable infrastructure rollout partnership mentioned in official DlicomApp public posts.',
    provenance: 'Observed from public X interaction citation on @DlicomApp public timeline.',
    confidenceScore: 68,
    discoverySource: 'Public X citation on @DlicomApp timeline',
    candidateReason: 'Publicly cited as Web3 infrastructure provider for Dlicom rollups on Base.',
    whyNotVerified: 'Third-party infrastructure partner rather than official Dlicom team or designated community leader on dlicom.io.',
    firstVerifiedAt: '2026-09-03T12:00:00Z',
    verifiedAt: '2026-09-03T12:00:00Z',
    lastVerifiedAt: '2026-09-03T12:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/0xZeeve',
    bio: 'Enterprise Web3 Infrastructure Automation Platform for Rollups and AppChains.',
  },
  {
    dliId: 'DLI-CAND-002',
    xHandle: 'dlicom_ambassador',
    normalizedHandle: 'dlicom_ambassador',
    displayName: 'Dlicom Ambassador Hub',
    role: 'Community Candidate',
    verificationLevel: 'COMMUNITY_CANDIDATE',
    verificationStatus: 'CANDIDATE',
    sourceType: 'PUBLIC_X_EVIDENCE',
    officialSourceUrl: 'https://dlicom.io/',
    evidenceUrls: [
      'https://dlicom.io/',
      'https://t.me/DlicomAppOfficial',
    ],
    evidenceSummary: 'Publicly observable regional ambassador initiative handle. Under verification by community leadership.',
    evidence: 'Publicly observable regional ambassador initiative handle. Under verification by community leadership.',
    provenance: 'Observed in regional community discussions on official Telegram hub.',
    confidenceScore: 62,
    discoverySource: 'Public community telegram handle reference',
    candidateReason: 'Direct bio reference claiming Dlicom regional ambassador representation.',
    whyNotVerified: 'Awaiting cryptographic or core-team roster confirmation on dlicom.io.',
    firstVerifiedAt: '2026-09-03T14:00:00Z',
    verifiedAt: '2026-09-03T14:00:00Z',
    lastVerifiedAt: '2026-09-03T14:00:00Z',
    sourceFreshness: 'FRESH',
    status: 'ACTIVE',
    avatarUrl: 'https://unavatar.io/x/dlicom_ambassador',
    bio: 'Community advocacy and regional support for Dlicom SocialFi on Base.',
  },
];

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', ['GET']);
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const view = req.query?.view || 'verified'; // 'verified' | 'candidates' | 'all'

  const membersMap = new Map();
  for (const m of OFFICIAL_SEED_MEMBERS) {
    membersMap.set(m.normalizedHandle, m);
  }

  // Load verified community members from Supabase if configured
  if (isSupabaseConfigured()) {
    try {
      const supabase = getSupabase();
      if (supabase) {
        const { data, error } = await supabase
          .from('dlicom_community_members')
          .select('*')
          .eq('verification_status', 'VERIFIED');

        if (!error && Array.isArray(data)) {
          for (const row of data) {
            const rawHandle = row.x_handle || row.x_username;
            if (rawHandle) {
              const clean = rawHandle.replace(/^@+/, '').trim().toLowerCase();
              membersMap.set(clean, {
                dliId: row.dli_id || `DLI-SUPA-${clean.substring(0, 6).toUpperCase()}`,
                xHandle: rawHandle,
                normalizedHandle: clean,
                displayName: row.display_name || clean,
                role: row.role || 'Verified Member',
                verificationLevel: row.verification_level || 'OFFICIALLY_VERIFIED',
                verificationStatus: 'VERIFIED',
                sourceType: row.source_type || 'OFFICIAL_WEBSITE',
                officialSourceUrl: row.official_source_url || 'https://dlicom.io/',
                evidenceUrls: row.evidence_urls || [row.official_source_url || 'https://dlicom.io/'],
                evidenceSummary: row.evidence_summary || row.evidence || 'Officially verified in Supabase registry.',
                evidence: row.evidence || 'Officially verified in Supabase registry.',
                provenance: row.provenance || 'Persisted in Supabase verified community registry.',
                confidenceScore: row.confidence_score || 95,
                discoverySource: row.discovery_source || 'dlicom verified database',
                firstVerifiedAt: row.first_verified_at || row.verified_at || new Date().toISOString(),
                verifiedAt: row.verified_at || new Date().toISOString(),
                lastVerifiedAt: row.last_verified_at || new Date().toISOString(),
                sourceFreshness: 'FRESH',
                status: row.status || 'ACTIVE',
                avatarUrl: row.avatar_url,
                bio: row.bio,
                region: row.region,
              });
            }
          }
        }
      }
    } catch {
      // Graceful fallback to official seed records
    }
  }

  const verifiedList = Array.from(membersMap.values());

  let returnMembers = verifiedList;
  if (view === 'candidates') {
    returnMembers = CANDIDATE_MEMBERS;
  } else if (view === 'all') {
    returnMembers = [...verifiedList, ...CANDIDATE_MEMBERS];
  }

  res.setHeader('Cache-Control', 'public, s-maxage=300, stale-while-revalidate=600');
  return res.status(200).json({
    status: 'ok',
    registryCount: returnMembers.length,
    totalVerified: verifiedList.length,
    totalCandidates: CANDIDATE_MEMBERS.length,
    view,
    source: 'dlicom-public-evidence-registry',
    members: returnMembers,
    candidates: CANDIDATE_MEMBERS,
  });
}
